version: "3.8"

services:
  shortly-db:
    image: postgres:15.4-bullseye
    restart: unless-stopped
    container_name: shortly-db
    env_file:
      - .env
    environment:
      - POSTGRES_DB=shortly
    ports:
      - 5432:5432
    volumes:
      - storage:/var/lib/postgresql/data
    networks:
      - internal

  db-manager:
    image: dpage/pgadmin4
    container_name: db-manager
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 15433:80
    volumes:
      - ./pgadmin-data/:/var/lib/pgadmin/
    networks:
      - internal
    depends_on:
      - shortly-db

  shortly:
    container_name: shortly
    restart: unless-stopped
    build:
      context: ../
      dockerfile: dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: development
      ConnectionStrings__DB: Server=shortly-db:5432;Database=shortly;User Id=postgres;Password=postgres
    depends_on:
      - shortly-db
    ports:
      - 5000:8080
    networks:
      - internal

volumes:
  storage:

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
